### PR TITLE
Adding internationalization

### PR DESCRIPTION
**Pull request by spiderxm**
Support for
- English
- German
- Russian

With menu to toggle between languages
Screenshot 2021-07-14 at 7 43 43 PM
Screenshot 2021-07-14 at 7 43 55 PM
Screenshot 2021-07-14 at 7 44 04 PM

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Thanks for the PR 👍 

* can you please convert these to YAML instead? you can use this site to convert JSON to YAML. https://www.json2yaml.com/
* should we also import this library inside the application (CLI)? if yes maybe we can have CLI argv option as well (default english) and have some tests in github CI to check the outputs.

thoughts?

**Comment by spiderxm** [comment]
yes we can use YAML it will be more clean.

**Comment by spiderxm** [comment]
for the CLI part i will take a look

**Comment by spiderxm** [comment]
@Ali-Razmjoo. @dhirensr  Please review

**Comment by Ali-Razmjoo** [comment]
ignore the error in regard of credential events; we fix that in elasticsearch branch 

image

**Pull request merged**
