### PR TITLE
Added dependencies versions

### PR DESCRIPTION
**Pull request by itsdivyanshjain**
#### Attempt to solve #226 in this PR. Added a dependencies version of python and python modules and apt packages in Dockerfile.

I have left apache2 and apche2-utils in http modules as it is (they probably not going to affect), if require do mention I will add it.

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
I think we must add them to something like `requirements.txt` so dependbot can access them and send dependency updates. what do you think?

**Comment by itsdivyanshjain** [comment]
So, I like the idea of requirements.txt. But how we differentiate apt package and python in requirements file.

**Comment by dhirensr** [comment]
@itsdivyanshjain : 

Since apt accepts input from stdin the simplest way to do it is:

$ cat requirement-apt.txt
gcc
cmake

$ apt install < requirement-apt.txt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by itsdivyanshjain** [comment]
Ok, you are saying to create different requirements file. If so, I will do that.

**Comment by itsdivyanshjain** [comment]
Closed this branch because of clutter. checkout PR #233

**Pull request closed without merging**
