### PR TITLE
Fix multiple import

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description 

While browsing through the Code and studying it for better understanding, I found minor bugs and anti-patterns that can be possibly improved to mitigate any potential bug. Since this is the first time, when I'm contributing to OWASP, I wanted to get a better understanding of the Codebase and make contributions on the same. 

## Changes Done 

The following commits have been made on the Codebase: 

- Fixing the multiple error issue

I found the `secure_smtpd` package was imported twice in the same file. I fixed it according to the PEP8 standard. There were some more issues with respect to PEP8 formatting as per PyLint but I would like to know, if PEP8 is strictly enforced on the Codebase.

### CODE REVIEW

**Comment by ChakshuGupta** [comment]
Hi Harsh,
Thank you for your contribution.
We are following PEP8 standards, flake8 linter is user for compliance check.
Could you please elaborate on the issues you find with respect to PEP8 formatting?

**Comment by HarshCasper** [comment]
> Hi Harsh,
> Thank you for your contribution.
> We are following PEP8 standards, flake8 linter is user for compliance check.
> Could you please elaborate on the issues you find with respect to PEP8 formatting?

Hi @ChakshuGupta 👋 

Thanks for the comment. I am yet to explore the whole Codebase, but PyLint caught these issues at first: 

- Wrong Import Order 
- Missing class docstring
- Unnecessary "elif" after "return"
- Unnecessary "else" after "raise"
- Too Long Lines

Besides that, I noticed some general issues like: 

- Unnecessary Literals used at places
- Unused Arguments in functions
- Exception Caught being very general
- Missing module docstrings 

I guess they might be false positives or something that shouldn't be a concern because I have used Flake8 just once with [this](https://github.com/harshcasper/webedge), so I would bank upon your opinion and decision about the same. 

It would be great if you can review this PR as well and suggest the way forward 🚀

**Comment by dhirensr** [comment]
Hello @HarshCasper ,
Thank you for your PR.
you could raise a separate PR to fix the issues that you have mentioned above.

**Review by dhirensr — APPROVED** [review]

**Review by ChakshuGupta — APPROVED** [review]

**Comment by Ali-Razmjoo** [comment]
thanks for the contribution, I merged the PR.

**Comment by Ali-Razmjoo** [comment]
oh I merged it to master, we should have merge this to development branch.

**Comment by Ali-Razmjoo** [comment]
@HarshCasper please re-create your PR for "development" branch.

**Pull request merged**
