### PR TITLE
WIP: Replace MongoDB with Elasticsearch

### PR DESCRIPTION
**Pull request by Ali-Razmjoo**
* [ ] write relevant documents in readme.md and update wiki

Get APIs to work

* [x] ./api/server.py:243:@app.route("/api/events/count/<event_type>", methods=["GET"])
* [x] ./api/server.py:272:@app.route("/api/events/count/groupby/<event_type>/<element>", methods=["GET"])
* [x] ./api/server.py:319:@app.route("/api/events/explore/<event_type>", methods=["GET"])
* [x] ./api/server.py:368:@app.route("/api/pcap/download", methods=["GET"])
* [x] ./api/server.py:394:@app.route("/api/core/list/modules", methods=["GET"])

### CODE REVIEW

**Comment by itsdivyanshjain** [comment]
@Ali-Razmjoo what are the reasons behind shifting to Elasticsearch from Mongodb.

**Comment by Ali-Razmjoo** [comment]
I want to experiment some integration with grafana and  splunk SIEM... they don't have much support for mongoDB

**Comment by dhirensr** [comment]
@Ali-Razmjoo  : I'm facing the error shown in the image, could you help with that?
error_ohp

**Comment by Ali-Razmjoo** [comment]
@dhirensr I added `:Z` flag for volumes, can you try again.

**Pull request merged**
