### PR TITLE
fix network_mode is incompatible with port_bindings Error

### PR DESCRIPTION
**Pull request by itsdivyanshjain**
Solved bug #243 by removing `port: 5000:5000` because it create conflict with `network_mode:host` in docker-compose-host.yml file.

Reference: https://forums.docker.com/t/docker-errors-invalidargument-host-network-mode-is-incompatible-with-port-bindings/103492

### CODE REVIEW

**Comment by itsdivyanshjain** [comment]
Now CI is failing because of mentioned requirements-apt-get issue #245

**Comment by ChakshuGupta** [comment]
@itsdivyanshjain This problem can be fixed by updating the library version in modules/ssh/strong_password/files/requirements-apt-get.txt file.
I have tested it on my system. If it works for you too, you can update it here in the PR.

**Comment by itsdivyanshjain** [comment]
@ChakshuGupta, I know that but when any apt package get updated then it's old version is not supported (shows Error that this version is not available) , so due to this our program gets break(that's why I am telling to add dependbot for that).

**Comment by ChakshuGupta** [comment]
@itsdivyanshjain I get what you mean.

@Ali-Razmjoo @dhirensr Do we need to have version numbers there? If it is not necessary, then the list file can be just the list of required packages without the version number.

**Comment by itsdivyanshjain** [comment]
Yes, even I am thinking of to get rid of version number in requirements-apt-get.txt

**Comment by Ali-Razmjoo** [comment]
if there isn't any proper solution, we can ignore the txt file for now, what do you guys think?

**Comment by itsdivyanshjain** [comment]
@Ali-Razmjoo 

we can do that also, but I think we can just remove the version number from requirements-apt-get file because whenever we/user need to add any apt package we can just edit requirements-apt-get file. Due to that it doesn't going to affect our code quality too.

**Comment by Ali-Razmjoo** [comment]
I am not sure if we remove the version we are going to face another issue once they get updated to latest... for now I'd like to fix the version to pass the CI and solve that issue in another PR/decision making process.

**Review by Ali-Razmjoo — APPROVED** [review]

**Comment by Ali-Razmjoo** [comment]
and thank you guys for contributions, tests and reports.

**Pull request merged**
